# MNIST

In [1]:
using SPN
using MNIST
using MultivariateStats

In [2]:
x, y = traindata()

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] Array(::Type{Float64}, ::Int64, ::Int64) at ./deprecated.jl:57
 [3] traindata() at /home/lefmann/.julia/v0.6/MNIST/src/MNIST.jl:88
 [4] include_string(::String, ::String) at ./loading.jl:515
 [5] include_string(::Module, ::String, ::String) at /home/lefmann/.julia/v0.6/Compat/src/Compat.jl:71
 [6] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/lefmann/.julia/v0.6/IJulia/src/execute_request.jl:158
 [7] (::Compat.#inner#17{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/lefmann/.julia/v0.6/Compat/src/Compat.jl:385
 [8] eventloop(::ZMQ.Socket) at /home/lefmann/.julia/v0.6/IJulia/src/eventloop.jl:8
 [9] (::IJulia.##14#17)() at ./task.jl:335
while loading In[2], in expression starting on line 1
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] Array(::Type{Float64}, ::Int64) at ./deprecated.jl:57
 [3] traindata() at /home/lefmann/.julia/v0.6/MNIST/src/MNIST.jl:8

([0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [5.0, 0.0, 4.0, 1.0, 9.0, 2.0, 1.0, 3.0, 1.0, 4.0  …  9.0, 2.0, 9.0, 5.0, 1.0, 8.0, 3.0, 5.0, 6.0, 8.0])

In [3]:
@show size(x)
@show size(y)

size(x) = (784, 60000)
size(y) = (60000,)


(60000,)

In [4]:
pcaModel = fit(PCA, x; maxoutdim=9)

PCA(indim = 784, outdim = 9, principalratio = 0.46458)

In [5]:
xTransformed = transform(pcaModel, x)

9×60000 Array{Float64,2}:
  123.933   1011.72     -51.8496   …  -178.053    130.606    -173.436 
  312.674    294.857   -392.173       -160.078      5.59194    24.7188
   24.5141  -596.34     188.51         257.613   -513.859    -556.019 
 -555.758   -460.766    521.011       -714.65     342.704    -120.862 
  -27.2967  -827.275   -306.681       -210.315   -521.166    -198.0   
  232.476    181.951      1.83535  …   462.463    540.554    -233.026 
  233.996    -45.0205  -859.047       -464.535   -107.376    -461.44  
 -159.799    104.97    -368.592        184.823   -140.729     154.455 
 -363.515     40.4591  -114.546        -87.5243   -16.4958     87.3036

In [6]:
# swap rows and columns:
x = xTransformed'

60000×9 Array{Float64,2}:
  123.933    312.674      24.5141  …   233.996   -159.799    -363.515 
 1011.72     294.857    -596.34        -45.0205   104.97       40.4591
  -51.8496  -392.173     188.51       -859.047   -368.592    -114.546 
 -799.127    607.197    -273.651      -473.713     67.3217    302.731 
 -382.755   -730.543     -16.3537      -91.6666   405.555     225.502 
  184.469   -221.332    -591.36    …   -31.6223   -98.5792    -47.0293
 -726.514    156.986     248.191       356.04     156.894    -226.846 
  513.345    310.773     104.08       -502.436   -250.842    -494.308 
 -868.907     81.5472    133.418       124.991    219.185    -229.229 
 -304.731   -465.597    -692.383      -446.21     -55.3147    -30.7534
 -146.202    643.426     251.311   …   395.08    -572.065    -106.959 
 -613.839    243.373    -344.926      -360.696    -47.2552    155.174 
  279.92     830.688    1106.71         62.1792  -373.897     454.063 
    ⋮                              ⋱               

# Normalize

Normalize the dataset such that each variable (column) has mean 0 and variance 1.

In [7]:
@show mean(x,1)
@show var(x,1);

mean(x, 1) = [-9.77404e-14 2.99527e-14 -4.75363e-14 -6.20882e-14 -4.02603e-14 2.18279e-14 -9.70128e-16 3.03165e-15 -1.5522e-14]
var(x, 1) = [3.32725e5 2.43284e5 2.11507e5 1.84776e5 1.66927e5 147845.0 1.12178e5 98874.4 94696.2]


In [8]:
function normalizeDataset!(x::AbstractArray)
    x = x .- mean(x,1)
    x = x
    return x ./ var(x,1)
end

normalizeDataset! (generic function with 1 method)

In [9]:
A = reshape(1:12, (3,4))
A = normalizeDataset!(A)
@show mean(A,1)
@show var(A,1);

mean(A, 1) = [0.0 0.0 0.0 0.0]
var(A, 1) = [1.0 1.0 1.0 1.0]


In [10]:
x = normalizeDataset!(x)

60000×9 Array{Float64,2}:
  0.000372478   0.00128522    0.000115902  …  -0.00161619   -0.00383875 
  0.00304071    0.00121199   -0.00281947       0.00106165    0.000427252
 -0.000155833  -0.001612      0.000891268     -0.00372788   -0.00120962 
 -0.00240177    0.00249584   -0.00129381       0.000680881   0.00319687 
 -0.00115037   -0.00300284   -7.732e-5         0.00410172    0.00238132 
  0.000554419  -0.000909768  -0.00279593   …  -0.000997014  -0.000496633
 -0.00218353    0.000645277   0.00117344       0.0015868    -0.00239551 
  0.00154285    0.00127741    0.000492089     -0.00253697   -0.00521994 
 -0.00261149    0.000335193   0.000630794      0.0022168    -0.00242068 
 -0.000915864  -0.0019138    -0.00327356      -0.000559444  -0.000324759
 -0.00043941    0.00264475    0.00118819   …  -0.00578577   -0.0011295  
 -0.00184489    0.00100037   -0.0016308       -0.000477931   0.00163865 
  0.000841296   0.00341448    0.00523248      -0.00378153    0.00479495 
  ⋮                      

In [11]:
spn = structureLearnPoon(x,3,3,nsum=5,nleaf=10,baseres=1)

Generating decompositions ... done
Generating SPN ...done


SumProductNetwork(size=2621)